language: node_js
node_js:
- '0.12'
matrix:
  fast_finish: true
sudo: false
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g grunt-cli
script:
- grunt build
deploy:
  -
    provider: releases
    api_key:
      secure: PCUejpQ1R8XNhynhzVslRp/RlKoneKOD72JP4UvnSfyycLTKLD5Dm6vgUrmN9H4XjnC68XvLUbfnzwIN4SAf0o0agU40EPHJV4avg7mgErYjxbtP6XkM49azWpcRD2T6FFm0syHAkL1LaXl7CcNwWTDMw5xspYwaXquXjMQJwUXuwxh8BkwUniX3wPR9R+nlX3Vt/xEKt5uIhPsjDFz1M3VNcW9WUUq/GNRw2zHrCWc7Wv7qaGsfBrxPg6XxSJ36MajcsYB70CMjdKn3X3fdeA/BzH8M9ukCJ77aS43taOrZ77VnYpjkqMMid8rvHdk5ef6RDETNbbQm+OevSB7CTtLHmJIEliSH+rnuK7pcQBQbPlDv0a5fCCNDYeuxQYkcWXa23ceuNMq5oGnugE1l8BTwoK9AxptiHlDS+RV49ZrBFStbO29RwLerEGV5LkrxMhcrrE+zGzrWKBlc5NM8fld4eA8aX2bog1mul+NvF6YnKptsZjzbslBTAcTsNHi/ZCPpeRyawQtVvG1X5Dw9aJ7fhHPwSfvvBbPZvvKf+k+YV+DTPvA+UWmpDadn+EQwkw8FjRXGsmsi+aXtlRGqdoBY+b6ox+9l10DdXbX3X4rgTixYhFwy92oC3lsntTnUHu7ahXavHgxiAVd861cLeYh9KRUWo9/tKfSkLDKvap8=
    file:
      - dist/ng-page-title.js
      - dist/ng-page-title.min.js
    on:
      repo: riggerthegeek/ng-page-title
      tags: true
